import json

# JSON data (pasted from your provided input)
json_data = [
    {"Status": "", "Usage": {"InputTokens": 260, "TotalTokens": 261, "OutputTokens": 1}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "", "Usage": {"InputTokens": 260, "TotalTokens": 262, "OutputTokens": 2}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "", "Usage": {"InputTokens": 260, "TotalTokens": 263, "OutputTokens": 3}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 267, "OutputTokens": 7}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 271, "OutputTokens": 11}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 275, "OutputTokens": 15}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 279, "OutputTokens": 19}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 283, "OutputTokens": 23}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 287, "OutputTokens": 27}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 291, "OutputTokens": 31}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 295, "OutputTokens": 35}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 299, "OutputTokens": 39}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 303, "OutputTokens": 43}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 307, "OutputTokens": 47}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 311, "OutputTokens": 51}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 315, "OutputTokens": 55}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 319, "OutputTokens": 59}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1.", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 323, "OutputTokens": 63}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 327, "OutputTokens": 67}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 331, "OutputTokens": 71}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 335, "OutputTokens": 75}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 339, "OutputTokens": 79}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 343, "OutputTokens": 83}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 347, "OutputTokens": 87}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 351, "OutputTokens": 91}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 355, "OutputTokens": 95}, "commands": [], "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 359, "OutputTokens": 99}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 363, "OutputTokens": 103}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 367, "OutputTokens": 107}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 371, "OutputTokens": 111}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 375, "OutputTokens": 115}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 379, "OutputTokens": 119}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 383, "OutputTokens": 123}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 387, "OutputTokens": 127}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 391, "OutputTokens": 131}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 395, "OutputTokens": 135}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 399, "OutputTokens": 139}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 403, "OutputTokens": 143}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么可能属于正当防卫", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 407, "OutputTokens": 147}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么可能属于正当防卫，但这需要具体", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 411, "OutputTokens": 151}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么可能属于正当防卫，但这需要具体情境下的判断。", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 415, "OutputTokens": 155}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么可能属于正当防卫，但这需要具体情境下的判断。  \n\n结果分析", "Round": 0, "Success": True, "httpStatusCode": 200},
    {"Status": "正在为您生成回答...", "Usage": {"InputTokens": 260, "TotalTokens": 419, "OutputTokens": 159}, "RequestId": "D68B868A-5FD4-5B46-9B7C-BCB26B7C81EB", "ResponseMarkdown": "  \n从你的描述来看，你和姐姐之间存在持续的冲突，且她多次在发生争执后向警方报案，声称你对她造成了伤害。这种情况可能涉及家庭内部纠纷以及法律层面的指控问题。你需要明确以下几点：  \n\n1. **是否存在真实的身体伤害**：如果她在冲突中确实受伤，并且有医疗记录或证据支持，这可能会对你不利。  \n2. **她的行为是否属于恶意举报**：如果她故意夸大事实或捏造伤害事实进行虚假指控，这本身也可能构成违法行为。  \n3. **自我防卫的界限**：如果你的行为是为了阻止她的攻击并保护自己，那么可能属于正当防卫，但这需要具体情境下的判断。  \n\n结果分析", "Round": 0, "Success": True, "httpStatusCode": 200}
]

def format_markdown(text):
    # Remove leading/trailing whitespace and convert \n to actual newlines
    text = text.strip().replace("\\n", "\n")
    # Split by newlines and filter out empty lines for cleaner output
    lines = [line for line in text.split("\n") if line.strip()]
    # Join lines with proper newlines, preserving markdown (bold **, italic *)
    return "\n".join(lines)

def extract_and_print_markdown(data):
    results = []
    last_two_items = data[-1:]
    for index, item in enumerate(last_two_items, start=len(data)-1):
        markdown = item.get("ResponseMarkdown", "")
        if markdown:  # Only process non-empty markdown
            formatted_text = format_markdown(markdown)
            results.append(f"Item {index + 1}:\n{formatted_text}\n{'-' * 50}")
    
    return "\n".join(results)

if __name__ == "__main__":
   a=extract_and_print_markdown(json_data)
   print(a)